spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        recordExceptions:
          - java.lang.Exception
    instances:
      gateway-cloud-web-01:
        baseConfig: default
      gateway-cloud-web-02:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      gateway-cloud-web-01:
        baseConfig: default
      gateway-cloud-web-02:
        baseConfig: default


#starter:
micro-service:
  starter:
    #    # starter-log4j2 配置
    #    log4j2:
    #      # 异常信息最大长度
    #      ex-max-length: 1024
    #      time-based-triggering-policy:
    #        # 多久滚动一次
    #        interval: 24
    #      size-based-triggering-policy:
    #        # 超过该大小就触发日志文件滚动更新
    #        size: 1MB
    #      default-rollover-strategy:
    #        # 同一文件夹下文件数量到达该数量开始覆盖
    #        max: 7
