server:
  # 开启优雅停机，默认值：immediate 为立即关闭
  shutdown: graceful
  # 服务端口
  port: 8001
  servlet:
    context-path: /cloud-web-01

spring:
  profiles:
    active: dev
  lifecycle:
    # 停机缓冲时间，默认：30秒
    timeout-per-shutdown-phase: 30s
  cloud:
    # 禁用ribbon。 Spring Cloud Loadbalancer 将替代 ribbon
    loadbalancer:
      ribbon:
        enable: false

# 暴露 actuator 端点
# 还需要在拦截器中排除 /actuator/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


# Feign 的相关配置
feign:
  # feign 开启 gzip 压缩
  compression:
    # 对请求进行压缩
    request:
      enabled: true
      # 针对以下类型的数据进行压缩
      mime-types: text/xml,application/xml,application/json
      # 大于1M的数据才进行压缩
      min-request-size: 1024
    # 响应时进行压缩
    response:
      enabled: true
  client:
    config:
      default:
        # 日志级别，取值：NONE、BASIC、HEADERS、FULL，源码位置 feign.Logger.Level
        loggerLevel: BASIC
#        # feign默认超时时间
#        connectTimeout: 2000
#        readTimeout: 5000
#        writeTimeout: 5000
  # 禁用默认的 http
  httpclient:
    enabled: false
  # 启用 okhttp。
  # feign.okhttp.OkHttpClient.execute打断点查看是否启用okhttp
  okhttp:
    enabled: true
  # 打开 Sentinel 对 Feign 的支持
  sentinel:
    enabled: true



#starter:
micro-service:
  starter:
    mybatis-plus:
      enabled: false
    # starter-web 配置
    web:
      logging:
        requestResponseLog: true
        includeHeaders: false

    # starter-spring-doc 配置
    spring-doc:
      title: cloud-web-01的API
    # starter-log4j2 配置
#    log4j2:
#      # 异常信息最大长度
#      ex-max-length: 1024
#      time-based-triggering-policy:
#        # 多久滚动一次
#        interval: 24
#      size-based-triggering-policy:
#        # 超过该大小就触发日志文件滚动更新
#        size: 1MB
#      default-rollover-strategy:
#        # 同一文件夹下文件数量到达该数量开始覆盖
#        max: 7