server:
  # 开启优雅停机，默认值：immediate 为立即关闭
  shutdown: graceful
  # 服务端口
  port: 10001
  servlet:
    context-path: /boot-web

spring:
  application:
    name: boot-web
  profiles:
    active: dev
  lifecycle:
    # 停机缓冲时间，默认：30秒
    timeout-per-shutdown-phase: 10s

# 暴露 actuator 端点
# 还需要在拦截器中排除 /actuator/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.github.codingsoldier.example.bootweb
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
