
server:
  port: 10100

spring:
  application:
    name: spring-boot-admin-server
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.1.121:8848
        namespace: namespace-example-dev
#        metadata:
#          user.name: admin
#          user.password: 123456
#  security:
#    user:
#      name: root
#      password: root
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
        include: '*'
  endpoint:
    health:
      show-details: always