server:
  # 服务端口
  port: 8002
  servlet:
    context-path: /boot-springdoc

spring:
  application:
    name: boot-springdoc
  datasource:
    url: ##########
    username: easygo
    password: Vr@Dev123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 200
      # 空闲时保持最小连接数
      minimum-idle: 20
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1

springdoc:
  swagger-ui:
    doc-expansion: none
  pre-loading-enabled: true
#  packages-to-scan: com.github.codingsoldier.example.springdoc
