server:
  # 服务端口
  port: 8002
  servlet:
    context-path: /boot-springdoc

spring:
  application:
    name: boot-springdoc
  datasource:
    username: root
    password: cpq..123
    url: jdbc:mysql://localhost:3306/cpq?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 200
      # 空闲时保持最小连接数
      minimum-idle: 20
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1

springdoc:
  pre-loading-enabled: true
  packages-to-scan: com.github.codingsoldier.example.springdoc