server:
  # 开启优雅停机，默认值：immediate 为立即关闭
  shutdown: graceful
  # 服务端口
  port: 8002
  servlet:
    context-path: /cloud-web-02

spring:
  profiles:
    active: dev
  lifecycle:
    # 停机缓冲时间，默认：30秒
    timeout-per-shutdown-phase: 10s

# 暴露 actuator 端点
# 还需要在拦截器中排除 /actuator/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# Feign 的相关配置
feign:
  # feign 开启 gzip 压缩
  compression:
    # 对请求进行压缩
    request:
      enabled: true
      # 针对以下类型的数据进行压缩
      mime-types: text/xml,application/xml,application/json
      # 大于1M的数据才进行压缩
      min-request-size: 1024
    # 响应时进行压缩
    response:
      enabled: true
  # 禁用默认的 http
  httpclient:
    enabled: false
  # 启用 okhttp
  okhttp:
    enabled: true
  # 打开 Sentinel 对 Feign 的支持
  sentinel:
    enabled: true
