server:
  # 服务端口
  port: 8002
  servlet:
    context-path: /cloud-web-02

spring:
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        server-addr: 192.168.1.121:8848
        #        server-addr: nacos-dev.vanrui.com:80
        # server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850 # Nacos 集群服务器地址
        namespace: namespace-example-dev
  #        # 指定actuator端点的访问路径，因为我们上面配置了服务的前缀 context-path ，所以我们需要将它拼接上，不然路径不对会报错
  #        # spring-boot-admin配置
  #        metadata:
  #          management:
  #            context-path: ${server.servlet.context-path}/actuator

  # sleuth + zipkin 分布式链路追踪
  sleuth:
    sampler:
      # ProbabilityBasedSampler 抽样策略
      probability: 1.0  # 采样比例, 1.0 表示 100%, 默认是 0.1
      # RateLimitingSampler 抽样策略, 设置了限速采集, spring.sleuth.sampler.probability 属性值无效
      rate: 100  # 每秒间隔接受的 trace 量
#  zipkin:
#    sender:
#      # 指定通过什么类型发送消息 默认是 web
#      type: WEB
#    # 指定 zipkin 的地址
#    base-url: http://localhost:10103/

# 暴露 actuator 端点
# 还需要在拦截器中排除 /actuator/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 50000
  eager-load:
    enabled: true
    clients: cloud-web

# Feign 的相关配置
feign:
  # feign 开启 gzip 压缩
  compression:
    # 对请求进行压缩
    request:
      enabled: true
      # 针对以下类型的数据进行压缩
      mime-types: text/xml,application/xml,application/json
      # 大于1M的数据才进行压缩
      min-request-size: 1024
    # 响应时进行压缩
    response:
      enabled: true
  # 禁用默认的 http
  httpclient:
    enabled: false
  # 启用 okhttp
  okhttp:
    enabled: true